# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m06xn7GvO8I5blSHNz9duLKh0PwVTDv5
"""

class Student:
    def __init__(self, id, name, year, subjects, total):
        self.id = id
        self.name = name
        self.year = year
        self.subjects = subjects
        self.total = total

    def display_info(self):
        print(f"Welcome, {self.name}!")
        print(f"You are in year: {self.year}")
        print(f"Your subjects are: {self.subjects}")
        print(f"Your total degree is: {self.total}")

        if int(self.total) > 250:
            print("Congratulations, you are passed!")

class StudentDatabase:
    def __init__(self):
        self.students = {}

    def add_student(self, student):
        self.students[student.id] = student

    def get_student(self, id):
        return self.students.get(id)

    def display_student_info(self, id):
        student = self.get_student(id)
        if student:
            student.display_info()
        else:
            print("Student not found!")

    def remove_student(self, id):
        if id in self.students:
            del self.students[id]
            print(f"Student with ID {id} removed successfully!")
        else:
            print(f"Student with ID {id} not found!")

    def edit_student(self, id):
        student = self.get_student(id)
        if student:
            print("Edit student information:")
            name = input("Enter new name (or press Enter to keep current): ")
            if name:
                student.name = name
            year = input("Enter new year (or press Enter to keep current): ")
            if year:
                student.year = year
            subjects = input("Enter new subjects (or press Enter to keep current): ")
            if subjects:
                student.subjects = eval(subjects)
            total = input("Enter new total degree (or press Enter to keep current): ")
            if total:
                student.total = total
            print(f"Student with ID {id} updated successfully!")
        else:
            print(f"Student with ID {id} not found!")

# Create a student database
db = StudentDatabase()

# Add students to the database
db.add_student(Student("1000", "Ahmed", "1", {"arabic": "30", "english": "20", "math": "10", "science": "40", "social": "50"}, "150"))
db.add_student(Student("2000", "Ali", "2", {"arabic": "50", "english": "60", "math": "80", "science": "90", "social": "80"}, "360"))
db.add_student(Student("3000", "Omar", "3", {"arabic": "70", "english": "80", "math": "80", "science": "80", "social": "90"}, "400"))
#Edit a student
edit_id = input("Enter the ID of the student to edit: ")
db.edit_student(edit_id)

# Display student information
db.display_student_info("1000")
db.display_student_info("2000")
db.display_student_info("3000")

# Remove a student
remove_id = input("Enter the ID of the student to remove: ")
db.remove_student(remove_id)